version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    restart: always
    #environment:
    #  - "MYSQL_ROOT_PASSWORD=123456"
    #  - "MYSQL_DATABASE=firefly"
    #  - "TZ=Asia/Shanghai"
    env_file:
      - ./env/mysql.env
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/log:/var/log/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./init/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always