version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/log:/var/log/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./init/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  yapi-mongo:
    image: mongo:latest
    # 容器名称
    container_name: standalone-mongo
    env_file:
      - ./env/yapi-mongo.env
    #挂载 宿主机路径:容器路劲
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/yapi/mongo/data:/data/db
      - /data/yapi/mongo/log:/var/log/mongodb
      - ./init/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    expose:
      - 27017 
  yapi:
    image: jayfong/yapi:1.9.1
    # 容器名称
    container_name: standalone-yapi
    env_file:
      - ./env/yapi.env
    volumes:
      - /data/yapi/log/yapi.log:/tmp/yapi.log
      - ./config/yapi/config.json:/api/config.json
    ports:
      - 3000:3000
    depends_on:
      - yapi-mongo
    restart: always