version: '1'
services: 
  mysql:
    image: mysql:8.0.32
    restart: always
    container_name: firefly_mysql
    volumes:
      - ../volumes/data/mysqldata:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./init/mysql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=firefly"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306